### ISSUE TITLE
Extra Hearts Disappearing until Relog.

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#44]
### Your Pack Version

1.5.4

### Type of Instance

Multiplayer

### Your Expectation

-

### The Reality

Extra Hearts gained from foods are not kept when going back to the overworld from the End.

### Your Proposal

Extra Hearts gained from food should be kept when going back to the overworld from the End.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Can it be desync?

**Comment by SwedishKaito** [comment]
No clue, and apparently XP is somewhat reset too, I got 119 levels from killing the dragons ..., 0 upon coming back to the overworld and I only have 19 levels when relogging.

**Comment by DrParadox7** [comment]
Likely the same issue:
-https://www.reddit.com/r/feedthebeast/comments/tsj916/stoneblock_losing_xp_when_going_between_dimensions/
-https://www.reddit.com/r/feedthebeast/comments/2me31f/dw20_17_losing_levelsxp_when_leaving_the_end/ 
-https://www.reddit.com/r/feedthebeast/comments/3qlp5k/any_way_to_preserve_xp_from_the_end_without/

Unlikely to be caused by the pack
